from allauth.account import views as allauth_views
from django.urls import include, path, re_path
from user_sessions import views as user_sessions_views

from routechoices.dashboard import views

urlpatterns = [
    path("", views.home_view, name="home_view"),
    path("participations", views.participations_view, name="participations_view"),
    path(
        "request-invite",
        views.club_request_invite_view,
        name="request_club_invite_view",
    ),
    path(
        "account/",
        include(
            (
                [
                    path("", views.account_edit_view, name="edit_view"),
                    path("emails", views.email_view, name="email_list"),
                    path(
                        "change-password",
                        allauth_views.password_change,
                        name="password_change_view",
                    ),
                    path("delete", views.account_delete_view, name="delete_view"),
                    path(
                        "sessions/",
                        include(
                            (
                                [
                                    path(
                                        "",
                                        view=user_sessions_views.SessionListView.as_view(),
                                        name="list_view",
                                    ),
                                    path(
                                        "delete-others",
                                        view=views.CustomSessionDeleteOtherView.as_view(),
                                        name="delete_other_view",
                                    ),
                                ],
                                "dashboard_account_session",
                            ),
                            namespace="session",
                        ),
                    ),
                ],
                "dashboard_account",
            ),
            namespace="account",
        ),
    ),
    path(
        "clubs/",
        include(
            (
                [
                    path("", views.club_select_view, name="select_view"),
                    path("new", views.club_create_view, name="create_view"),
                    re_path(
                        r"^(?P<club_slug>[A-Za-z0-9_-]+)/",
                        include(
                            [
                                path(
                                    "",
                                    views.club_view,
                                    name="edit_view",
                                ),
                                path(
                                    "custom-domain",
                                    views.club_custom_domain_view,
                                    name="custom_domain_view",
                                ),
                                path(
                                    "delete",
                                    views.club_delete_view,
                                    name="delete_view",
                                ),
                                path(
                                    "send-invite",
                                    views.club_invite_add_view,
                                    name="send_invite_view",
                                ),
                                path("upgrade", views.upgrade, name="upgrade_view"),
                                path(
                                    "devices/",
                                    include(
                                        (
                                            [
                                                path(
                                                    "",
                                                    views.device_list_view,
                                                    name="list_view",
                                                ),
                                                path(
                                                    "csv",
                                                    views.device_list_download,
                                                    name="list_download",
                                                ),
                                                path(
                                                    "new",
                                                    views.device_add_view,
                                                    name="add_view",
                                                ),
                                            ],
                                            "dashboard_club_device",
                                        ),
                                        namespace="device",
                                    ),
                                ),
                                path(
                                    "maps/",
                                    include(
                                        (
                                            [
                                                path(
                                                    "",
                                                    views.map_list_view,
                                                    name="list_view",
                                                ),
                                                path(
                                                    "new",
                                                    views.map_create_view,
                                                    name="create_view",
                                                ),
                                                path(
                                                    "draw",
                                                    views.map_draw_view,
                                                    name="draw_view",
                                                ),
                                                path(
                                                    "upload-kmz",
                                                    views.map_kmz_upload_view,
                                                    name="upload_kmz_view",
                                                ),
                                                path(
                                                    "upload-gpx",
                                                    views.map_gpx_upload_view,
                                                    name="upload_gpx_view",
                                                ),
                                                re_path(
                                                    r"(?P<map_id>[A-Za-z0-9_-]+)/",
                                                    include(
                                                        [
                                                            path(
                                                                "",
                                                                views.map_edit_view,
                                                                name="edit_view",
                                                            ),
                                                            path(
                                                                "delete",
                                                                views.map_delete_view,
                                                                name="delete_view",
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                            ],
                                            "dashboard_club_map",
                                        ),
                                        namespace="map",
                                    ),
                                ),
                                path(
                                    "events/",
                                    include(
                                        (
                                            [
                                                path(
                                                    "",
                                                    views.event_list_view,
                                                    name="list_view",
                                                ),
                                                path(
                                                    "new",
                                                    views.event_create_view,
                                                    name="create_view",
                                                ),
                                                path(
                                                    "quick-start",
                                                    views.quick_event,
                                                    name="quick_start_view",
                                                ),
                                                re_path(
                                                    r"^(?P<event_id>[A-Za-z0-9_-]+)/",
                                                    include(
                                                        [
                                                            path(
                                                                "",
                                                                views.event_edit_view,
                                                                name="edit_view",
                                                            ),
                                                            path(
                                                                "competitors",
                                                                views.event_competitors_view,
                                                                name="competitors_view",
                                                            ),
                                                            path(
                                                                "competitors-printer-friendly",
                                                                views.event_competitors_printer_view,
                                                                name="competitors_printer_view",
                                                            ),
                                                            path(
                                                                "delete",
                                                                views.event_delete_view,
                                                                name="delete_view",
                                                            ),
                                                            path(
                                                                "route-upload",
                                                                views.event_route_upload_view,
                                                                name="route_upload_view",
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                            ],
                                            "dashboard_club_event",
                                        ),
                                        namespace="event",
                                    ),
                                ),
                                path(
                                    "event-sets/",
                                    include(
                                        (
                                            [
                                                path(
                                                    "",
                                                    views.event_set_list_view,
                                                    name="list_view",
                                                ),
                                                path(
                                                    "new",
                                                    views.event_set_create_view,
                                                    name="create_view",
                                                ),
                                                re_path(
                                                    r"(?P<event_set_id>[A-Za-z0-9_-]+)/",
                                                    include(
                                                        [
                                                            path(
                                                                "",
                                                                views.event_set_edit_view,
                                                                name="edit_view",
                                                            ),
                                                            path(
                                                                "delete",
                                                                views.event_set_delete_view,
                                                                name="delete_view",
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                            ],
                                            "dashboard_club_event_set",
                                        ),
                                        namespace="event_set",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                "dashboard_club",
            ),
            namespace="club",
        ),
    ),
    path(
        "media/",
        include(
            (
                [
                    re_path(
                        r"^maps/(?P<map_id>[-0-9a-zA-Z_]{11})$",
                        views.dashboard_map_download,
                        name="map_download",
                    ),
                    re_path(
                        r"^logos/(?P<club_id>[-0-9a-zA-Z_]{11})$",
                        views.dashboard_logo_download,
                        name="logo_download",
                    ),
                    re_path(
                        r"^banners/(?P<club_id>[-0-9a-zA-Z_]{11})$",
                        views.dashboard_banner_download,
                        name="banner_download",
                    ),
                    re_path(
                        r"^geojson/(?P<event_id>[-0-9a-zA-Z_]{11})$",
                        views.dashboard_geojson_download,
                        name="geojson_download",
                    ),
                ],
                "dashboard_media",
            ),
            namespace="media",
        ),
    ),
    path("hijack/release/", views.MyReleaseUserView.as_view(), name="hijack_release"),
]
