services:
  db:
    container_name: rc_postgres
    image: postgres:15.1
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    expose:
      - "5432"
  minio:
    container_name: rc_minio
    image: minio/minio:latest
    volumes:
      - ../media:/data
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command:
      - server
      - /data
  smtp:
    container_name: rc_mailpit
    image: axllent/mailpit:latest
    expose:
      - "1025"
    ports:
      - 8025:8025
    volumes:
      - ./media:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  nginx:
    container_name: rc_nginx
    image: rphlo/nginx:latest
    ports:
      - "443:443/udp"
      - "443:443/tcp"
    volumes:
      - ../static:/static:ro
      - ../letsencrypt/:/etc/nginx/ssl:ro
      - ../nginx/routechoices.conf:/etc/nginx/conf.d/routechoices.conf:ro
    links:
      - minio
      - django
    command: ['nginx', '-g', 'daemon off;']
  django:
    container_name: rc_django
    image: rphlo/routechoices-dev-server
    stop_signal: SIGINT
    volumes:
      - ../:/app/:rw
    ports:
      - "2000:2000"
      - "2001:2001"
      - "2002:2002"
      - "2003:2003"
    expose:
      - "2000"
      - "2002"
    links:
      - db
      - minio
      - smtp
    command: ["gunicorn", "-c", "bin/gunicorn.conf.py", "--bind", ":8000", "--workers", "${NUM_PROCESSES:-3}", "--threads", "${NUM_PROCESSES:-3}", "--reload", "routechoices.${WSGI_FILE:-wsgi}:application",]
