# Generated by Django 5.1.1 on 2024-10-24 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_rename_usersetting_usersettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                models.F("frontpage_featured"), name="core_on_frontpage_idx"
            ),
        ),
    ]
