# Generated by Django 5.1.1 on 2024-10-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_club_core_on_frontpage_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tcpdevicecommand",
            name="comment",
            field=models.CharField(blank=True, default=""),
        ),
    ]
