# Generated by Django 5.1.1 on 2024-11-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_alter_tcpdevicecommand_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotdevice",
            name="device",
        ),
        migrations.DeleteModel(
            name="SpotFeed",
        ),
        migrations.DeleteModel(
            name="SpotDevice",
        ),
    ]
