# Generated by Django 5.1.3 on 2025-01-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_remove_spotdevice_device_delete_spotfeed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="subscription_paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
