# Generated by Django 5.1.3 on 2025-01-24 06:49

from django.db import migrations, models

import routechoices.core.models
import routechoices.lib.storages


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_club_subscription_paused_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="geojson_layer",
            field=models.FileField(
                blank=True,
                help_text="GeoJSON CSS Layer",
                null=True,
                storage=routechoices.lib.storages.OverwriteImageStorage(
                    aws_s3_bucket_name="routechoices"
                ),
                upload_to=routechoices.core.models.geojson_upload_path,
            ),
        ),
    ]
