# Generated by Django 5.1.3 on 2025-01-24 08:55

from django.db import migrations, models

import routechoices.core.models
import routechoices.lib.storages


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_event_geojson_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="geojson_layer",
            field=models.FileField(
                blank=True,
                help_text="GeoJSON CSS Layer",
                null=True,
                storage=routechoices.lib.storages.OverwriteImageStorage(
                    aws_s3_bucket_name="routechoices"
                ),
                upload_to=routechoices.core.models.geojson_upload_path,
                verbose_name="GeoJSON Layer",
            ),
        ),
    ]
