# Generated by Django 5.1.5 on 2025-03-12 11:36

import django.db.models.deletion
from django.db import migrations, models

import routechoices.lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_alter_event_geojson_layer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotFeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.CharField(max_length=64, unique=True)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpotDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "messenger_id",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[routechoices.lib.validators.validate_esn],
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spot_device",
                        to="core.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "spot device",
                "verbose_name_plural": "spot devices",
                "ordering": ["messenger_id"],
            },
        ),
    ]
