# Generated by Django 5.2 on 2025-04-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_spotfeed_spotdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="owners",
            field=models.ManyToManyField(
                related_name="devices",
                through="core.DeviceClubOwnership",
                through_fields=("device", "club"),
                to="core.club",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="extra_maps",
            field=models.ManyToManyField(
                related_name="+",
                through="core.MapAssignation",
                through_fields=("event", "map"),
                to="core.map",
            ),
        ),
    ]
