# Generated by Django 5.2 on 2025-04-09 09:45

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_alter_device_owners_alter_event_extra_maps"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"),
                        "Enter a valid hex color, eg. #000000",
                        "invalid",
                    )
                ],
                verbose_name="Color",
            ),
        ),
    ]
