# Generated by Django 5.2 on 2025-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_competitor_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="tags",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="Categories"
            ),
        ),
    ]
