# Generated by Django 5.2 on 2025-04-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_competitor_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(db_index=True, verbose_name="Start Date (UTC)"),
        ),
    ]
