# Generated by Django 5.1.5 on 2025-04-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_alter_event_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="is_gpx",
            new_name="virtual",
        ),
    ]
