# Generated by Django 5.1.5 on 2025-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_rename_is_gpx_device_virtual"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "backdrop_map__in",
                        (
                            "blank",
                            "osm",
                            "gmap-street",
                            "gmap-hybrid",
                            "gmap-terrain",
                            "mapant-ee",
                            "mapant-fi",
                            "mapant-no",
                            "mapant-es",
                            "mapant-se",
                            "mapant-ch",
                            "topo-fi",
                            "topo-fr",
                            "topo-no",
                            "topo-uk",
                            "topo-world",
                            "topo-world-alt",
                        ),
                    )
                ),
                name="core_event_bgmap_valid",
            ),
        ),
    ]
