# Generated by Django 5.1.5 on 2025-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_event_core_event_bgmap_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="backdrop_map",
            field=models.CharField(
                choices=[
                    ("blank", "Blank"),
                    ("osm", "Open Street Map"),
                    ("gmap-street", "Google Map Street"),
                    ("gmap-hybrid", "Google Map Satellite"),
                    ("gmap-terrain", "Google Map Terrain"),
                    ("mapant-ee", "Mapant Estonia"),
                    ("mapant-fi", "Mapant Finland"),
                    ("mapant-no", "Mapant Norway"),
                    ("mapant-es", "Mapant Spain"),
                    ("mapant-se", "Mapant Sweden"),
                    ("mapant-ch", "Mapant Switzerland"),
                    ("topo-fi", "Topo Finland"),
                    ("topo-fr", "Topo France"),
                    ("topo-no", "Topo Norway"),
                    ("topo-uk", "Topo UK"),
                    ("topo-world", "Topo World (OpenTopo)"),
                    ("topo-world-alt", "Topo World (ArcGIS)"),
                ],
                default="blank",
                max_length=16,
                verbose_name="Background map",
            ),
        ),
    ]
