# Generated by Django 5.2.1 on 2025-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_alter_event_backdrop_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="gpsseuranta_known",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="gpsseuranta_relay_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
