# Generated by Django 5.2.3 on 2025-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_device_gpsseuranta_known_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deviceclubownership",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="eventset",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="deviceclubownership",
            constraint=models.UniqueConstraint(
                fields=("device", "club"), name="device_club_ownership_club_device_uc"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("club", "event_set", "name"),
                name="event_name_event_set_club_uc",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("club", "slug"), name="event_slug_club_uc"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventset",
            constraint=models.UniqueConstraint(
                fields=("name", "club"), name="event_set_name_club_uc"
            ),
        ),
    ]
