# Generated by Django 5.2.4 on 2025-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_alter_deviceclubownership_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Start time"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(db_index=True, verbose_name="Start Date"),
        ),
    ]
