# Generated by Django 5.2.8 on 2025-11-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_map__corners_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="is_personal_page",
            field=models.BooleanField(default=False),
        ),
    ]
